name: Daily build
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          path: 'sumatrapdf'
          ref: 'master'
          persist-credentials: false

      - name: Check out pdfprint source code
        uses: actions/checkout@v3
        with:
          path: 'pdfprint'
          ref: 'master'
          repository: 'kjk/pdfprint'
          token: ${{ secrets.BOT_GH_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: update pdfprint
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: dir && cd sumatrapdf && .\doit.bat -extract-utils -ci
